### ISSUE TITLE
macOS: Text input not visible if system setting 'Show scrollbars' is not 'when scrolling'

### ISSUE THREAD

**Issue by j6s** [yue/wey#3]
macOS has a system setting that allows controlling when scrollbars are visible (under system settings -> general). The three options are:

- When scrolling
    - Only shows scrollbars when the user scrolls. In this mode the scrollbars do not use any space and are only overlaid over the content.
- Always
    - Scrollbars are always visible to the user even if he is not actively scrolling. In this mode the scrollbar will take 15px (or so) of the content area in order to display a scrollbar there.
- Automatically based on mouse or trackpad
    - Uses 'When scrolling' for trackpads and 'Always' for mice

---

If the setting is set to 'Always' (or 'Automatic' when a mouse is used) then the 15px for a potential scrollbar are allocated at the bottom of the text input causing the input to be only about 5px high completely hiding the text that was typed.

![screen shot 2018-04-09 at 10 40 24 am](https://user-images.githubusercontent.com/3374170/38488038-72693230-3be2-11e8-8099-c72619bc2d5f.png)
![screen shot 2018-04-09 at 10 40 01 am](https://user-images.githubusercontent.com/3374170/38488039-7282270e-3be2-11e8-83f0-6bca6eb78d37.png)

**Comment by tuananh** [comment]
Thank you. This would work for now.
