### ISSUE TITLE
Enter adds line break

### ISSUE THREAD

**Issue by j6s** [yue/wey#37]
Wey adds a line break just before sending the message when you press enter while in the middle of a message.

**Steps to reproduce**
1. Enter a message (for example `test`)
2. Use backspace to move the cursor to the middle of the text
3. press enter

**Expected behaviour**
- The message is sent as is

**Actual behaviour**
- A line break is added and then the message is being sent

![linebreak](https://user-images.githubusercontent.com/3374170/38741204-aa9e4d52-3f39-11e8-84d5-883f413aedf2.gif)

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/wey/commit/0559c448835b22564391f6473a2984c115083f17.
