### ISSUE TITLE
Bug: Enter in input method editor

### ISSUE THREAD

**Issue by helloqiu** [yue/wey#38]
Pressing enter in the input method editor can output characters that has been input into it. But it also sends message in wey.  
https://github.com/yue/wey/blob/master/lib/view/chat-box.js#L202
I have a try to bind ``handleKeyUp`` to ``onKeyDown`` but **Enter** doesn't fire ``onKeyDown`` method.
![ezgif-4-5b461fea19-min](https://user-images.githubusercontent.com/8971659/38768086-c99034c2-4020-11e8-848e-29038aa787ef.gif)

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/wey/commit/0559c448835b22564391f6473a2984c115083f17.
