### ISSUE TITLE
Need help. Question. Project packaging and development.

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [yue/wey#42]
**Impressive work authors! Thank you!**

Could you please let us know whether it is possible to develop the same app as Wey in the following steps:
1. Creating a SPA written in [Vue.js](https://vuejs.org/) 
2. Prepacking it with [webpack](https://webpack.js.org/)? Webpack would allow us to do:
    - [tree-shaking](https://webpack.js.org/guides/tree-shaking/)
    - convenient ability to traspile ES 2015+ to JavaScript **making sure** that the targeted OSs would be able to run.
3. Packaging it with [yackage](https://github.com/yue/yackage) for different platforms

**Comment by zcbenz** [comment]
Essentially Wey is just a normal Node.js project, it just needs a special runtime to run. So yeah you can develop same GUI apps with any kind of transpiler.
