### ISSUE TITLE
blank channel after running for a long period of time

### ISSUE THREAD

**Issue by tuananh** [yue/wey#48]
i saw this error when inspect. reload didn't help but restarting did

```
TypeError: undefined is not an object (evaluating 'target.tagName.toLowerCase'
```

**Comment by zcbenz** [comment]
When inspecting the page, does the page have any element in it? I wonder if the webview crashed.

**Comment by tuananh** [comment]
That I don't know. It only happens after i signed in for a long time.

**Comment by zcbenz** [comment]
This seems to be related to the reconnecting policy, after running for a long period of time reconnecting could have very long delay, and messages would be blank in this case.
