### ISSUE TITLE
after message is sent, the view is not automatically scrolled down

### ISSUE THREAD

**Issue by tuananh** [yue/wey#50]
after message is sent, the view is not automatically scrolled down

**Comment by zcbenz** [comment]
Are you using v0.2.0 or starting from the source code?

**Comment by tuananh** [comment]
I build from source (latest)

**Comment by zcbenz** [comment]
Can you try if the latest commit works? I remember I fixed a similar problem before.

**Comment by tuananh** [comment]
It seems to be fixed. I can't reproduce it anymore. Thanks.
