### ISSUE TITLE
Feature: Resize text input for multiline text

### ISSUE THREAD

**Issue by j6s** [yue/wey#7]
By default the text input is 1 line in height.

If I type a message containing soft-breaks (shift-enter) then a new line is created in the input.

**Expected Result:**
The height of the input grows in order to display both lines

**Actual Result:**
The height of the input stays at 1 line showing only the lower line while hiding the upper line.

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/wey/commit/15255920393acca29f0d0e19d06b17c078a995e2.
