### ISSUE TITLE
Images and Files not showing up

### ISSUE THREAD

**Issue by Snazzyham** [yue/wey#74]
If a user sends me an image or attachment file in a DM, the message does not show up on wey, but opening it up on the slack web app shows up. Is this a limitation with the Slack API?

**Comment by ddobrev** [comment]
@zcbenz thank you for this application. I have been looking for a lean client for months. Could you please, however, let us know if you intend to continue your work? This issue as well as https://github.com/yue/wey/issues/72 are really necessary in order to have the default Slack client superseded.

**Comment by zcbenz** [comment]
@ddobrev I'm currently going through some big changes in my life, I'll continue working on this, but that will be about 6 months later.

**Comment by zcbenz** [comment]
Fixed in v0.3.2.
