### ISSUE TITLE
Support threads

### ISSUE THREAD

**Issue by ddobrev** [yue/wey#75]
We all badly need a fast performing client for Slack which this one is. Unfortunately, it does not support threads which makes it useless as much as needed. Please implement.

**Comment by zcbenz** [comment]
Theads is supported, please use a newer version.
<img width="252" alt="screen shot 2018-12-22 at 21 12 05" src="https://user-images.githubusercontent.com/639601/50374229-43f67b80-062e-11e9-934a-cb285d9cca29.png">

**Comment by ddobrev** [comment]
I'm afraid that this one isn't fully fixed. While threads do appear now, clicking the bubble for starting a thread does nothing. I use macOS 10.14.2.

**Comment by zcbenz** [comment]
Can you run Wey from Terminal and then try to start a thread in it, and post the output in Terminal if there is?

```
/Applications/Wey.app/Contents/MacOS/Wey
```

**Comment by zcbenz** [comment]
Are you opening thread in a channel, group or direct message?

Threads are not supported in direct messages, it is a bug that the bubble icon shows there.

**Comment by ddobrev** [comment]
It was in a direct message, so yes, the bubble does appear there.
