### ISSUE TITLE
Toggle Fullscreen on macOS

### ISSUE THREAD

**Issue by optikfluffel** [yue/wey#76]
Most apps on macOS can toggle their full screen mode with `Ctrl + Cmd + F` and it would be nice to have this in wey as well. This should also be available in the [`AppMenu`](https://github.com/yue/wey/blob/master/lib/view/app-menu.js), under a new submenu called `View`.

I would have sent a PR, but I can't get this Repo running on my machine.

**Comment by PerezArmando** [comment]
I want to work on this.
