### ISSUE TITLE
Freeze after mouseover DM 

### ISSUE THREAD

**Issue by Mizuho32** [yue/wey#79]
## Synopsis
As I mentioned in #78, I can launch the app before 4d18133 but the app got frozen after mouseover DM as shown below.
![outout](https://user-images.githubusercontent.com/5453161/50400920-2c55f900-07ce-11e9-9acf-ef5ad52a7885.gif)

## Environment

- OS: Manjaro(Arch Linux)
- Node: Node v8.11.4 (asdf-vm)

**Comment by zcbenz** [comment]
Minimal way to reproduce:
1. Open a direct message
2. Move mouse to chat window
3. Move mouse back

After simple debugging it seems that the `onMouseLeave` and `onMouseEnter` events of `ChannelItem` are emitting infinitely after hiding the exit button. This is a bug in yue library.

**Comment by zcbenz** [comment]
Fixed in v0.3.3.
